### ISSUE TITLE
Issue with demultiplexing using TAGGD. 

### ISSUE THREAD

**Issue by SalendraSingh** [SpatialTranscriptomicsResearch/st_pipeline#127]
Hi, 
I am getting this error message, even after making sure, all the required packages are installed, the genome is well-indexed, the files are downloaded from SRA.

Command Used : 
###############################################################################33333
 /mnt/pan/Data16/Tools/Anaconda/Environments/PY36/bin/python /mnt/pan/Data16/Tools/st_pipeline/st_pipeline/scripts/st_pipeline_run.py --ids /mnt/pan/Data4/local/sxs1528/Mito/Spatial/Salendra_Spatial/Input_File/GSE144239_ST_barcode_id.txt --ref-map /mnt/pan/Data16/sxs1528/REFERENCES/STAR/GRCH38/ --ref-annotation /mnt/pan/Data16/sxs1528/REFERENCES/STAR/GRCH38/Homo_sapiens.GRCh38.99.gtf --expName Spatial_Mito_SS --no-clean-up --verbose --threads 16 --log-file /mnt/pan/Data4/local/sxs1528/Mito/Spatial/Salendra_Spatial/Output_Folder/st_pipeline.log --output-folder /mnt/pan/Data4/local/sxs1528/Mito/Spatial/Salendra_Spatial/Output_Folder --temp-folder /mnt/pan/Data4/local/sxs1528/Mito/Spatial/Salendra_Spatial/TMP_Folder --keep-discarded-files /mnt/pan/Data4/local/sxs1528/Mito/Spatial/stpipeline_check/SRR11832808_1.fastq /mnt/pan/Data4/local/sxs1528/Mito/Spatial/stpipeline_check/SRR11832808_2.fastq
#############################################################################################################

Error Log 
############################################################################################
ST Pipeline, parameters loaded
ST Pipeline, logger created
ST Pipeline, sanity check passed. Starting the run.
Error running the pipeline
Error demultiplexing with TAGGD.
Output file is not present /mnt/pan/Data4/local/sxs1528/Mito/Spatial/Salendra_Spatial/TMP_Folder/demultiplexed_matched.bam
b'Traceback (most recent call last):\n  File "/mnt/pan/Data16/Tools/Anaconda/Environments/PY36/bin/taggd_demultiplex.py", line 4, in <module>\n    __import__(\'pkg_resources\').run_script(\'taggd==0.3.6\', \'taggd_demultiplex.py\')\n  File "/mnt/pan/Data16/Tools/Anaconda/Environments/PY36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 665, in run_script\n    self.require(requires)[0].run_script(script_name, ns)\n  File "/mnt/pan/Data16/Tools/Anaconda/Environments/PY36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1453, in run_script\n    .format(**locals()),\npkg_resources.ResolutionError: Script \'scripts/taggd_demultiplex.py\' not found in metadata at \'/mnt/pan/Data16/Tools/Anaconda/Environments/PY36/lib/python3.6/site-packages/taggd-0.3.6.dist-info\'\n'
##################################################################################################

Error Log from the file 

############################################################################################3333
WARNING:STPipeline:Pair reads found with different names SRR11832808.80057825.1 80057825 length=31 and SRR11832808.80057825.2 80057825 length=46
WARNING:STPipeline:Pair reads found with different names SRR11832808.80057826.1 80057826 length=31 and SRR11832808.80057826.2 80057826 length=46
WARNING:STPipeline:Pair reads found with different names SRR11832808.80057827.1 80057827 length=31 and SRR11832808.80057827.2 80057827 length=46
WARNING:STPipeline:Pair reads found with different names SRR11832808.80057828.1 80057828 length=31 and SRR11832808.80057828.2 80057828 length=46
WARNING:STPipeline:Pair reads found with different names SRR11832808.80057829.1 80057829 length=31 and SRR11832808.80057829.2 80057829 length=46
WARNING:STPipeline:Pair reads found with different names SRR11832808.80057830.1 80057830 length=31 and SRR11832808.80057830.2 80057830 length=46
WARNING:STPipeline:Pair reads found with different names SRR11832808.80057831.1 80057831 length=31 and SRR11832808.80057831.2 80057831 length=46
WARNING:STPipeline:Pair reads found with different names SRR11832808.80057832.1 80057832 length=31 and SRR11832808.80057832.2 80057832 length=46
WARNING:STPipeline:Pair reads found with different names SRR11832808.80057833.1 80057833 length=31 and SRR11832808.80057833.2 80057833 length=46
WARNING:STPipeline:Pair reads found with different names SRR11832808.80057834.1 80057834 length=31 and SRR11832808.80057834.2 80057834 length=46
WARNING:STPipeline:Pair reads found with different names SRR11832808.80057835.1 80057835 length=31 and SRR11832808.80057835.2 80057835 length=46
WARNING:STPipeline:Pair reads found with different names SRR11832808.80057836.1 80057836 length=31 and SRR11832808.80057836.2 80057836 length=46
WARNING:STPipeline:Pair reads found with different names SRR11832808.80057837.1 80057837 length=31 and SRR11832808.80057837.2 80057837 length=46
WARNING:STPipeline:Pair reads found with different names SRR11832808.80057838.1 80057838 length=31 and SRR11832808.80057838.2 80057838 length=46
INFO:STPipeline:Trimming stats total reads (pair): 80057838
INFO:STPipeline:Trimming stats 9544025 reads have been dropped!
INFO:STPipeline:Trimming stats you just lost about 11.92% of your data
INFO:STPipeline:Trimming stats reads remaining: 70513813
INFO:STPipeline:Trimming stats dropped pairs due to incorrect UMI: 0
INFO:STPipeline:Trimming stats dropped pairs due to low quality UMI: 133139
INFO:STPipeline:Trimming stats dropped pairs due to high AT content: 3393505
INFO:STPipeline:Trimming stats dropped pairs due to high GC content: 985826
INFO:STPipeline:Trimming stats dropped pairs due to presence of artifacts: 4542605
INFO:STPipeline:Trimming stats dropped pairs due to being too short: 488950
INFO:STPipeline:Starting genome alignment 2022-01-18 19:03:40.174870
INFO:STPipeline:Mapping stats: 
INFO:STPipeline:Mapping stats are computed from all the pair reads present in the raw files
INFO:STPipeline:                   Uniquely mapped reads number |	49424497
INFO:STPipeline:                        Uniquely mapped reads % |	70.09%
INFO:STPipeline:        Number of reads mapped to multiple loci |	16457190
INFO:STPipeline:             % of reads mapped to multiple loci |	23.34%
INFO:STPipeline:                 % of reads unmapped: too short |	5.81%
INFO:STPipeline:Total mapped reads: 65881687
INFO:STPipeline:Starting barcode demultiplexing 2022-01-18 19:21:52.523586
ERROR:STPipeline:Error demultiplexing with TAGGD.
Output file is not present /mnt/pan/Data4/local/sxs1528/Mito/Spatial/Salendra_Spatial/TMP_Folder/demultiplexed_matched.bam
b'Traceback (most recent call last):\n  File "/mnt/pan/Data16/Tools/Anaconda/Environments/PY36/bin/taggd_demultiplex.py", line 4, in <module>\n    __import__(\'pkg_resources\').run_script(\'taggd==0.3.6\', \'taggd_demultiplex.py\')\n  File "/mnt/pan/Data16/Tools/Anaconda/Environments/PY36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 665, in run_script\n    self.require(requires)[0].run_script(script_name, ns)\n  File "/mnt/pan/Data16/Tools/Anaconda/Environments/PY36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1453, in run_script\n    .format(**locals()),\npkg_resources.ResolutionError: Script \'scripts/taggd_demultiplex.py\' not found in metadata at \'/mnt/pan/Data16/Tools/Anaconda/Environments/PY36/lib/python3.6/site-packages/taggd-0.3.6.dist-info\'\n'
#####################################################################################################33

I am not sure what's creating this issue, Any help in this regard would be grateful 

Thanks and regards,

Salendra 

################################################################################################

**Comment by jfnavarro** [comment]
Hi @SalendraSingh and thanks for posting this! Are you using the correct barcodes (ids) file? and the correct barcode settings? It looks like TaggD is unable to demultiple any read.
