### ISSUE TITLE
undefined symbol: _intel_fast_memcmp

### ISSUE THREAD

**Issue by xianliaogithub** [SpatialTranscriptomicsResearch/st_pipeline#131]
when I run the st_pipeline_run.py, it shows 
Traceback (most recent call last):
  File "/hpcwork/nm514167/dbitseq_rna/st_pipeline_run.py", line 22, in <module>
    from stpipeline.core.pipeline import Pipeline
  File "/home/nm514167/miniconda3/envs/Dbit/lib/python3.7/site-packages/stpipeline/core/pipeline.py", line 12, in <module>
    from stpipeline.common.dataset import createDataset
  File "/home/nm514167/miniconda3/envs/Dbit/lib/python3.7/site-packages/stpipeline/common/dataset.py", line 13, in <module>
    from stpipeline.common.unique_events_parser import parse_unique_events
ImportError: /home/nm514167/miniconda3/envs/Dbit/lib/python3.7/site-packages/stpipeline/common/unique_events_parser.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _intel_fast_memcmp

I don't know what's the problem and how to fix it.

**Comment by xianliaogithub** [comment]
this issue was fixed.
